# Generated by Django 2.2.10 on 2020-05-30 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image1',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/brands/'),
        ),
    ]
