# Generated by Django 2.2.5 on 2020-01-12 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='No department', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subdepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='No subdepartment', max_length=100)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.Department')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='subdepartment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.Subdepartment'),
        ),
        migrations.AddField(
            model_name='product',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.Department'),
        ),
        migrations.AddField(
            model_name='product',
            name='subdepartment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.Subdepartment'),
        ),
    ]
