# Generated by Django 2.2.10 on 2020-05-31 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_brand_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Inactive'), (2, 'Active'), (3, 'Finished')], default=1),
        ),
        migrations.AlterField(
            model_name='discountline',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Inactive'), (2, 'Active'), (3, 'Finished')], default=1),
        ),
    ]
