# Generated by Django 2.2.10 on 2020-05-31 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200531_1459'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscountStatus',
        ),
    ]
