# Generated by Django 2.2.10 on 2020-06-05 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200605_2237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productrating',
            old_name='rating',
            new_name='score',
        ),
    ]
