# Generated by Django 2.2.10 on 2020-06-14 23:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0008_auto_20200606_0123'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productrating',
            unique_together={('product', 'user')},
        ),
    ]
