# Generated by Django 2.2.5 on 2020-02-06 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200206_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='thumbimage',
            new_name='thumbnail',
        ),
    ]
