# Generated by Django 2.2.10 on 2020-06-30 11:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0011_productreviewed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductReviewed',
            new_name='LastViewedProducts',
        ),
    ]
