# Generated by Django 2.2.5 on 2020-02-06 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20200206_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description2',
        ),
    ]
