# Generated by Django 2.2.10 on 2020-07-14 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20200630_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='enddate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='discount',
            name='startdate',
            field=models.DateTimeField(),
        ),
    ]
