# Generated by Django 2.2.10 on 2020-07-15 21:59

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20200715_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image1',
            field=models.ImageField(upload_to='pic_folder/brands/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image1',
            field=models.ImageField(upload_to='pic_folder/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image2',
            field=models.ImageField(upload_to='pic_folder/'),
        ),
        migrations.AlterField(
            model_name='department',
            name='image1',
            field=models.ImageField(upload_to='pic_folder/'),
        ),
        migrations.AlterField(
            model_name='department',
            name='image2',
            field=models.ImageField(upload_to='pic_folder/'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='description',
            field=models.CharField(blank=True, default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discount',
            name='image',
            field=models.ImageField(upload_to='pic_folder/'),
        ),
        migrations.AlterField(
            model_name='discountprioritytype',
            name='description',
            field=models.CharField(blank=True, default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discountprioritytype',
            name='name',
            field=models.CharField(default='Priority name', max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='discounted_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', editable=False, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(upload_to='pic_folder/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='pic_folder/'),
        ),
        migrations.AlterField(
            model_name='subdepartment',
            name='image1',
            field=models.ImageField(upload_to='pic_folder/'),
        ),
        migrations.AlterField(
            model_name='subdepartment',
            name='image2',
            field=models.ImageField(upload_to='pic_folder/'),
        ),
    ]
