# Generated by Django 2.2.10 on 2020-08-26 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20200715_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subdepartment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub', to='products.Subdepartment'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='priority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.DiscountPriorityType'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.DiscountType'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Department'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subdepartment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Subdepartment'),
        ),
        migrations.AlterField(
            model_name='subdepartment',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Department'),
        ),
    ]
