# Generated by Django 2.2.5 on 2020-04-23 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20200317_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='slug',
            field=models.SlugField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subdepartment',
            name='slug',
            field=models.SlugField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
