# Generated by Django 2.2.5 on 2020-04-26 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20200426_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryimage',
            old_name='product',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='departmentimage',
            old_name='product',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='subdepartmentimage',
            old_name='product',
            new_name='subdepartment',
        ),
    ]
