# Generated by Django 2.2.5 on 2020-04-26 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20200426_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentimage',
            name='department',
        ),
        migrations.RemoveField(
            model_name='subdepartmentimage',
            name='subdepartment',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/'),
        ),
        migrations.AddField(
            model_name='department',
            name='image',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/'),
        ),
        migrations.AddField(
            model_name='subdepartment',
            name='image',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/'),
        ),
        migrations.DeleteModel(
            name='CategoryImage',
        ),
        migrations.DeleteModel(
            name='DepartmentImage',
        ),
        migrations.DeleteModel(
            name='SubdepartmentImage',
        ),
    ]
