# Generated by Django 2.2.5 on 2020-04-26 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20200426_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='image',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='subdepartment',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='category',
            name='image2',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/'),
        ),
        migrations.AddField(
            model_name='department',
            name='image2',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/'),
        ),
        migrations.AddField(
            model_name='subdepartment',
            name='image2',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/'),
        ),
    ]
