# Generated by Django 2.2.5 on 2020-04-27 17:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20200426_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountPriorityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Priority name', max_length=150)),
                ('value', models.IntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('description', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiscountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Discount type name', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Discount name', max_length=150)),
                ('set_id', models.IntegerField()),
                ('value', models.FloatField(validators=[django.core.validators.MaxValueValidator(0.99), django.core.validators.MinValueValidator(0.01)])),
                ('startdate', models.DateTimeField()),
                ('enddate', models.DateTimeField()),
                ('description', models.CharField(default='Discount name', max_length=300)),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.DiscountPriorityType')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.DiscountType')),
            ],
        ),
    ]
