# Generated by Django 2.2.5 on 2020-04-27 22:39

from django.db import migrations, models
import products.validators


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_discount_discountprioritytype_discounttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCustom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(validators=[products.validators.ProductIDsValidator])),
            ],
        ),
        migrations.AlterField(
            model_name='discount',
            name='description',
            field=models.CharField(default='Discount description', max_length=300),
        ),
        migrations.AlterField(
            model_name='discounttype',
            name='name',
            field=models.CharField(default='Discount type name', max_length=150, unique=True),
        ),
    ]
