# Generated by Django 2.2.5 on 2020-04-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_auto_20200427_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountprioritytype',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
