# Generated by Django 2.2.5 on 2020-04-27 23:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_auto_20200427_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='value',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(1)]),
        ),
    ]
