# Generated by Django 2.2.5 on 2020-04-27 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_auto_20200427_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
