# Generated by Django 2.2.5 on 2020-04-28 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_auto_20200427_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='discounttype',
            name='model',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='DiscountLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Discount')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
    ]
