# Generated by Django 2.2.5 on 2020-04-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_auto_20200428_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='discounttype',
            name='lookup_field',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
