# Generated by Django 2.2.5 on 2020-04-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_discounttype_lookup_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discounttype',
            name='lookup_field',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
    ]
