# Generated by Django 2.2.5 on 2020-04-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_auto_20200428_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcustom',
            name='name',
            field=models.CharField(default='Custom product list', max_length=150),
        ),
    ]
