# Generated by Django 2.2.5 on 2020-04-29 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_discountcustom_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Inactive', max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='discount',
            name='status',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.DiscountStatus'),
        ),
    ]
