# Generated by Django 2.2.5 on 2020-04-29 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_auto_20200429_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='status',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, to='products.DiscountStatus'),
        ),
        migrations.AlterField(
            model_name='discountstatus',
            name='name',
            field=models.CharField(default='Inactive', editable=False, max_length=15),
        ),
    ]
