# Generated by Django 2.2.5 on 2020-04-29 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_auto_20200429_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountline',
            name='status',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, to='products.DiscountStatus'),
        ),
    ]
