# Generated by Django 2.2.5 on 2020-04-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0042_auto_20200430_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='enddate',
            field=models.DateTimeField(default='2020-06-05 15:00:00.000'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='startdate',
            field=models.DateTimeField(default='2020-04-05 15:00:00.000'),
        ),
    ]
