# Generated by Django 2.2.5 on 2020-04-30 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0043_auto_20200430_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='enddate',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 0, 0)),
        ),
        migrations.AlterField(
            model_name='discount',
            name='startdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 17, 0, 0)),
        ),
    ]
