# Generated by Django 2.2.5 on 2020-04-30 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0044_auto_20200430_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountProductList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.TextField(null=True)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Discount')),
            ],
        ),
    ]
