# Generated by Django 2.2.5 on 2020-05-03 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0045_discountproductlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='status',
            field=models.ForeignKey(default=2, editable=False, on_delete=django.db.models.deletion.PROTECT, to='products.DiscountStatus'),
        ),
    ]
