# Generated by Django 2.2.10 on 2020-05-08 20:14

from django.db import migrations, models
import django.utils.timezone
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0046_auto_20200503_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='creationdate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='discounted_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', editable=False, max_digits=14, null=True),
        ),
    ]
