# Generated by Django 2.2.10 on 2020-05-18 11:47

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0048_auto_20200511_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reservation',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
