# Generated by Django 2.2.10 on 2020-05-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20200530_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='promo_code',
            field=models.BooleanField(null=True),
        ),
    ]
