# Generated by Django 2.2.10 on 2020-05-30 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_promo_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='promo_code',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='cart.PromoCode'),
        ),
    ]
