# Generated by Django 2.2.10 on 2020-05-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='booked',
        ),
        migrations.RemoveField(
            model_name='order',
            name='confirmed',
        ),
        migrations.AlterField(
            model_name='order',
            name='access_code',
            field=models.SmallIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(editable=False, max_length=20),
        ),
    ]
