# Generated by Django 2.2.5 on 2020-04-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20200420_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='session_key',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
