# Generated by Django 2.2.10 on 2020-05-29 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_promocode_minimum_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocode',
            old_name='minimum_value',
            new_name='minimum_order_value',
        ),
    ]
