# Generated by Django 2.2.5 on 2020-04-20 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20200420_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='session_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sessions.Session'),
        ),
    ]
