# Generated by Django 2.2.5 on 2020-04-20 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20200420_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='owner',
        ),
    ]
