# Generated by Django 2.2.10 on 2020-05-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20200529_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
