# Generated by Django 2.2.10 on 2020-05-29 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_promocode_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocode',
            old_name='status',
            new_name='active',
        ),
    ]
