# Generated by Django 2.2.10 on 2020-05-15 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_shipment_shipmenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='email',
            field=models.EmailField(default='test@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='first_name',
            field=models.CharField(default='Michal', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='last_name',
            field=models.CharField(default='Tolkacz', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Shipment before payment'), (2, 'Shipment paid and during preparation'), (4, 'Shipment delivered to client'), (3, 'Shipment sent to client')], default=1),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.ShipmentType'),
        ),
    ]
