# Generated by Django 2.2.10 on 2020-05-15 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_auto_20200515_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.Order', unique=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Shipment before payment'), (4, 'Shipment delivered to client'), (3, 'Shipment sent to client'), (2, 'Shipment paid and during preparation')], default=1),
        ),
    ]
