# Generated by Django 2.2.10 on 2020-05-15 23:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_auto_20200515_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='creationdate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivereddate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='preparationdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='sentdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Shipment sent to client'), (2, 'Shipment paid and during preparation'), (4, 'Shipment delivered to client'), (1, 'Shipment before payment')], default=1),
        ),
    ]
