# Generated by Django 2.2.10 on 2020-05-16 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_auto_20200516_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Paid and during preparation'), (1, 'New and before payment'), (3, 'Sent to client'), (4, 'Delivered to client')], default=1),
        ),
    ]
