# Generated by Django 2.2.10 on 2020-05-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_auto_20200516_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='access_key',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Sent to client'), (1, 'New and before payment'), (4, 'Delivered to client'), (2, 'Paid and during preparation')], default=1),
        ),
    ]
