# Generated by Django 2.2.10 on 2020-05-17 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('cart', '0016_auto_20200516_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'New and before payment'), (3, 'Sent to client'), (4, 'Delivered to client'), (2, 'Paid and during preparation')], default=1),
        ),
        migrations.CreateModel(
            name='OrderAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.Order')),
                ('session_key', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='sessions.Session')),
            ],
        ),
    ]
