# Generated by Django 2.2.10 on 2020-05-18 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0017_auto_20200517_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Delivered to client'), (2, 'Paid and during preparation'), (3, 'Sent to client'), (1, 'New and before payment')], default=1),
        ),
    ]
