# Generated by Django 2.2.10 on 2020-05-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0018_auto_20200518_0217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='access_key',
            new_name='access_code',
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'New and before payment'), (4, 'Delivered to client'), (2, 'Paid and during preparation'), (3, 'Sent to client')], default=1),
        ),
    ]
