# Generated by Django 2.2.10 on 2020-05-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0019_auto_20200518_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Delivered to client'), (2, 'Paid and during preparation'), (1, 'New and before payment'), (3, 'Sent to client')], default=1),
        ),
    ]
