# Generated by Django 2.2.10 on 2020-05-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0021_auto_20200518_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Sent to client'), (2, 'Paid and during preparation'), (1, 'New and before payment'), (4, 'Delivered to client')], default=1),
        ),
    ]
