# Generated by Django 2.2.10 on 2020-05-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0022_auto_20200518_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='is_ordered',
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Delivered to client'), (2, 'Paid and during preparation'), (3, 'Sent to client'), (1, 'New and before payment')], default=1),
        ),
    ]
