# Generated by Django 2.2.10 on 2020-05-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0023_auto_20200518_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Sent to client'), (4, 'Delivered to client'), (1, 'New and before payment'), (2, 'Paid and during preparation')], default=1),
        ),
    ]
