# Generated by Django 2.2.10 on 2020-05-18 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0024_auto_20200518_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'New and before payment'), (2, 'Paid and during preparation'), (3, 'Sent to client'), (4, 'Delivered to client')], default=1),
        ),
    ]
